version: "3"
services:
  admin-server:
    image: pekspb/admin-server
    restart: on-failure
    ports:
    - 9003:9003
    env_file:
      - admin-server.env

  client-service:
    image: pekspb/client-service
    restart: on-failure
    ports:
    - 8080:8080
    env_file:
      - client-service.env
    depends_on:
      - admin-server
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    env_file:
      - mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    env_file:
    - mongo-express.env
    depends_on:
      - mongo



